### ISSUE TITLE
Mentioned on MDN Docs

### ISSUE THREAD

**Issue by ruggi99** [kudla/promise-status-async#17]
Hi, this is not a issue.
This is only to inform you that you are mentioned on MDN Docs as an example of `Promise.race`.
[Link here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race#using_promise.race_to_detect_the_status_of_a_promise)

Hope this looks good to you.

**Comment by kudla** [comment]
That's all good 👍
